-- Autogenerated lua file by the Spyface tool
-- 'Wimps and posers -- leave the hall! -- ManOwaR
--
-- DO NOT HAND EDIT.
--
local tiles =
{
    {
        x = 3,
        y = 1,
        zone = [[ko_security]],
        variant = 1,
        dynamic_impass = 1,
    },
    {
        x = 3,
        y = 2,
        zone = [[ko_security]],
        variant = 1,
    },
    {
        x = 4,
        y = 1,
        zone = [[ko_security]],
        variant = 1,
    },
    {
        x = 4,
        y = 2,
        zone = [[ko_security]],
        variant = 1,
    },
    {
        x = 2,
        y = 1,
        zone = [[ko_security]],
        variant = 1,
        dynamic_impass = 1,
    },
    {
        x = 2,
        y = 2,
        zone = [[ko_security]],
        variant = 1,
    },
    {
        x = 5,
        y = 1,
        zone = [[ko_security]],
        variant = 1,
    },
    {
        x = 5,
        y = 2,
        zone = [[ko_security]],
        variant = 1,
    },
    {
        x = 5,
        y = 3,
        zone = [[ko_security]],
        variant = 1,
    },
    {
        x = 2,
        y = 3,
        zone = [[ko_security]],
        variant = 1,
    },
    {
        x = 3,
        y = 3,
        zone = [[ko_security]],
        variant = 1,
    },
    {
        x = 4,
        y = 3,
        zone = [[ko_security]],
        variant = 1,
    },
    {
        x = 1,
        y = 1,
        zone = [[ko_security]],
        variant = 1,
    },
    {
        x = 1,
        y = 2,
        zone = [[ko_security]],
        variant = 1,
    },
    {
        x = 1,
        y = 3,
        zone = [[ko_security]],
        variant = 1,
    },
    {
        x = 5,
        y = 4,
        variant = 0,
    },
    {
        x = 4,
        y = 4,
        variant = 0,
    },
    {
        x = 3,
        y = 4,
        variant = 0,
    },
    {
        x = 2,
        y = 4,
        variant = 0,
    },
    {
        x = 1,
        y = 4,
        variant = 0,
    },
    {
        x = 5,
        y = 5,
        variant = 0,
    },
    {
        x = 4,
        y = 5,
        variant = 0,
    },
    {
        x = 3,
        y = 5,
        variant = 0,
    },
    {
        x = 1,
        y = 5,
        variant = 0,
    },
    {
        x = 2,
        y = 5,
        variant = 0,
    },
}
local walls =
{
    {
        x = 4,
        y = 0,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 4,
        y = 1,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 3,
        y = 0,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 3,
        y = 1,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 2,
        y = 0,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 2,
        y = 1,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 5,
        y = 0,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 5,
        y = 1,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 1,
        y = 0,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 1,
        y = 1,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 6,
        y = 1,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 5,
        y = 1,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 6,
        y = 2,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 5,
        y = 2,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 6,
        y = 3,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 5,
        y = 3,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 5,
        y = 3,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 5,
        y = 4,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 4,
        y = 3,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 4,
        y = 4,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 2,
        y = 3,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 2,
        y = 4,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 1,
        y = 3,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 1,
        y = 4,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 1,
        y = 3,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 0,
        y = 3,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 1,
        y = 2,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 0,
        y = 2,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 1,
        y = 1,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 0,
        y = 1,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 3,
        y = 3,
        wallIndex = [[security_door]],
        dir = 2,
    },
    {
        x = 3,
        y = 4,
        wallIndex = [[security_door]],
        dir = 6,
    },
}
local units =
{
    {
        maxCount = 2,
        spawnChance = 1,
        {
            {
                x = 3,
                y = 1,
                template = [[lab_safe]],
                unitData =
                {
                    facing = 2,
                },
            },
            1,
        },
        {
            {
                x = 2,
                y = 1,
                template = [[lab_safe]],
                unitData =
                {
                    facing = 2, lootWeight = 2,
                },
            },
            1,
        },
    },
}
local decos =
{
}
local lights =
{
}
local sounds =
{
}
local export =
{
    cgraph =
    {
        edges =
        {
            {
                id0 = 0,
                x0 = 6,
                y0 = 1,
                id1 = 1,
                x1 = 5,
                y1 = 1,
            },
            {
                id0 = 2,
                x0 = 6,
                y0 = 2,
                id1 = 1,
                x1 = 5,
                y1 = 2,
            },
            {
                id0 = 3,
                x0 = 6,
                y0 = 3,
                id1 = 1,
                x1 = 5,
                y1 = 3,
            },
            {
                id0 = 1,
                x0 = 1,
                y0 = 3,
                id1 = 4,
                x1 = 0,
                y1 = 3,
            },
            {
                id0 = 1,
                x0 = 1,
                y0 = 2,
                id1 = 5,
                x1 = 0,
                y1 = 2,
            },
            {
                id0 = 1,
                x0 = 1,
                y0 = 1,
                id1 = 6,
                x1 = 0,
                y1 = 1,
            },
            {
                id0 = 1,
                x0 = 3,
                y0 = 2,
                id1 = 107,
                x1 = 3,
                y1 = 1,
            },
            {
                id0 = 1,
                x0 = 4,
                y0 = 1,
                id1 = 107,
                x1 = 3,
                y1 = 1,
            },
            {
                id0 = 8,
                x0 = 3,
                y0 = 0,
                id1 = 107,
                x1 = 3,
                y1 = 1,
            },
            {
                id0 = 1,
                x0 = 2,
                y0 = 2,
                id1 = 107,
                x1 = 2,
                y1 = 1,
            },
            {
                id0 = 9,
                x0 = 2,
                y0 = 0,
                id1 = 107,
                x1 = 2,
                y1 = 1,
            },
            {
                id0 = 1,
                x0 = 1,
                y0 = 1,
                id1 = 107,
                x1 = 2,
                y1 = 1,
            },
        },
    },
    width = 5,
    height = 5,
    version = 1,
    tiles = tiles,
    walls = walls,
    units = units,
    decos = decos,
    lights = lights,
    sounds = sounds,
}
return export
