-- Autogenerated lua file by the Spyface tool
-- 'Wimps and posers -- leave the hall! -- ManOwaR
--
-- DO NOT HAND EDIT.
--
local STRINGS =
{
    DEVELOPED_BY = "Developed by Klei Entertainment",
    
    NAMES =
    {
        "Jeff Agala",
        "Mike Bell",
        "Aaron Bouthillier",
        "Bruce Chang",
        "Jamie Cheng",
        "Vangelis Christou",
        "Alex Colbert",
        "Allan Cortez",
        "Chris Costa",
        "Vince De Vera",
        "Jason Dreger",
        "Stephanie Faye",
        "Kevin Forbes",
        "Nana Fujino",
        "Kelly Graham",
        "Tatham Johnson",
        "Paul Ku",
        "James Lantz",
        "Cheoljoo Lee",
        "Wade Lindley",
        "Matthew Marteinsson",
        "Charlie McKenna",
        "Brook Miles",
        "Michael Rodriguez",
        "Corey Rollins",
        "Alex Savin",
        "Meghan Shaw",
        "Eugene Trakhtenberg",
        "Will Turnbull",
        "Joe Wreggelsworth",
        "Nabie-ah Yousuf",
    },
}

return STRINGS