-- Autogenerated lua file by the Spyface tool
-- 'Wimps and posers -- leave the hall! -- ManOwaR
--
-- DO NOT HAND EDIT.
--
local tiles =
{
    {
        x = 2,
        y = 1,
        variant = 0,
        impass = 1,
        cover = 1,
    },
    {
        x = 3,
        y = 1,
        variant = 0,
        impass = 1,
        cover = 1,
    },
    {
        x = 2,
        y = 2,
        variant = 1,
        impass = 1,
        cover = 1,
    },
    {
        x = 3,
        y = 2,
        variant = 1,
    },
    {
        x = 2,
        y = 3,
        variant = 1,
        tags =
        {
            "letter_spawn",
        },
    },
    {
        x = 3,
        y = 3,
        variant = 1,
    },
    {
        x = 1,
        y = 1,
        variant = 0,
        impass = 1,
        cover = 1,
        sightblock = 1,
    },
    {
        x = 1,
        y = 2,
        variant = 0,
    },
    {
        x = 1,
        y = 3,
        variant = 0,
        impass = 1,
        cover = 1,
    },
    {
        x = 1,
        y = 4,
        variant = 0,
        impass = 1,
        cover = 1,
    },
    {
        x = 3,
        y = 4,
        variant = 0,
    },
    {
        x = 2,
        y = 4,
        variant = 0,
    },
}
local walls =
{
}
local units =
{
}
local decos =
{
    {
        x = 1,
        y = 2,
        kanim = [[ftm_lab_trashcan1]],
        facing = 6,
    },
    {
        x = 3,
        y = 1,
        kanim = [[ftm_lab_steeltable2]],
        facing = 2,
    },
    {
        x = 2,
        y = 2,
        kanim = [[ftm_lab_postgizmo1]],
        facing = 2,
    },
    {
        x = 1,
        y = 1,
        kanim = [[ftm_lab_closet1]],
        facing = 2,
    },
    {
        x = 1,
        y = 4,
        kanim = [[decor_ftm_lab_flooring_1x1panel1]],
        facing = 4,
    },
    {
        x = 3,
        y = 4,
        kanim = [[decor_ftm_lab_flooring_1x1panel0]],
        facing = 6,
    },
    {
        x = 2,
        y = 1,
        kanim = [[decor_ftm_lab_flooring_1x1alt5]],
        facing = 6,
    },
    {
        x = 1,
        y = 3,
        kanim = [[ftm_lab_console3]],
        facing = 0,
    },
}
local lights =
{
}
local sounds =
{
}
local export =
{
    cgraph =
    {
        edges =
        {
            {
                id0 = 1,
                x0 = 2,
                y0 = 0,
                id1 = 100,
                x1 = 2,
                y1 = 1,
            },
            {
                id0 = 2,
                x0 = 3,
                y0 = 2,
                id1 = 100,
                x1 = 3,
                y1 = 1,
            },
            {
                id0 = 3,
                x0 = 4,
                y0 = 1,
                id1 = 100,
                x1 = 3,
                y1 = 1,
            },
            {
                id0 = 4,
                x0 = 3,
                y0 = 0,
                id1 = 100,
                x1 = 3,
                y1 = 1,
            },
            {
                id0 = 2,
                x0 = 2,
                y0 = 3,
                id1 = 100,
                x1 = 2,
                y1 = 2,
            },
            {
                id0 = 2,
                x0 = 3,
                y0 = 2,
                id1 = 100,
                x1 = 2,
                y1 = 2,
            },
            {
                id0 = 5,
                x0 = 1,
                y0 = 2,
                id1 = 100,
                x1 = 2,
                y1 = 2,
            },
            {
                id0 = 5,
                x0 = 1,
                y0 = 2,
                id1 = 100,
                x1 = 1,
                y1 = 1,
            },
            {
                id0 = 6,
                x0 = 1,
                y0 = 0,
                id1 = 100,
                x1 = 1,
                y1 = 1,
            },
            {
                id0 = 7,
                x0 = 0,
                y0 = 1,
                id1 = 100,
                x1 = 1,
                y1 = 1,
            },
            {
                id0 = 2,
                x0 = 2,
                y0 = 3,
                id1 = 108,
                x1 = 1,
                y1 = 3,
            },
            {
                id0 = 5,
                x0 = 1,
                y0 = 2,
                id1 = 108,
                x1 = 1,
                y1 = 3,
            },
            {
                id0 = 9,
                x0 = 0,
                y0 = 3,
                id1 = 108,
                x1 = 1,
                y1 = 3,
            },
            {
                id0 = 10,
                x0 = 1,
                y0 = 5,
                id1 = 108,
                x1 = 1,
                y1 = 4,
            },
            {
                id0 = 2,
                x0 = 2,
                y0 = 4,
                id1 = 108,
                x1 = 1,
                y1 = 4,
            },
            {
                id0 = 11,
                x0 = 0,
                y0 = 4,
                id1 = 108,
                x1 = 1,
                y1 = 4,
            },
        },
    },
    width = 3,
    height = 4,
    version = 1,
    tiles = tiles,
    walls = walls,
    units = units,
    decos = decos,
    lights = lights,
    sounds = sounds,
}
return export
