-- Autogenerated lua file by the Spyface tool
-- 'Wimps and posers -- leave the hall! -- ManOwaR
--
-- DO NOT HAND EDIT.
--
local tiles =
{
    {
        x = 1,
        y = 2,
        variant = 0,
    },
    {
        x = 1,
        y = 3,
        variant = 0,
    },
    {
        x = 1,
        y = 4,
        variant = 0,
        dynamic_impass = 1,
    },
    {
        x = 2,
        y = 2,
        variant = 0,
        deployIndex = 1,
        deployFacing = 0,
    },
    {
        x = 2,
        y = 3,
        variant = 0,
        deployIndex = 1,
        deployFacing = 0,
    },
    {
        x = 2,
        y = 4,
        variant = 0,
    },
    {
        x = 1,
        y = 5,
        variant = 0,
    },
    {
        x = 2,
        y = 5,
        variant = 0,
    },
    {
        x = 3,
        y = 2,
        variant = 0,
        deployIndex = 1,
        deployFacing = 0,
    },
    {
        x = 3,
        y = 3,
        variant = 0,
        deployIndex = 1,
        deployFacing = 0,
    },
    {
        x = 3,
        y = 4,
        variant = 0,
    },
    {
        x = 3,
        y = 5,
        variant = 0,
    },
    {
        x = 1,
        y = 1,
        variant = 0,
    },
    {
        x = 2,
        y = 1,
        variant = 0,
        deployIndex = 1,
        deployFacing = 0,
    },
    {
        x = 3,
        y = 1,
        variant = 0,
        deployIndex = 1,
        deployFacing = 0,
    },
}
local walls =
{
    {
        x = 1,
        y = 2,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 0,
        y = 2,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 1,
        y = 3,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 0,
        y = 3,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 1,
        y = 4,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 0,
        y = 4,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 1,
        y = 5,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 0,
        y = 5,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 1,
        y = 1,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 0,
        y = 1,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 2,
        y = 0,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 2,
        y = 1,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 3,
        y = 0,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 3,
        y = 1,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 1,
        y = 0,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 1,
        y = 1,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 4,
        y = 1,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 3,
        y = 1,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 4,
        y = 2,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 3,
        y = 2,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 4,
        y = 3,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 3,
        y = 3,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 4,
        y = 4,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 3,
        y = 4,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 4,
        y = 5,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 3,
        y = 5,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 3,
        y = 5,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 3,
        y = 6,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 2,
        y = 5,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 2,
        y = 6,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 1,
        y = 5,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 1,
        y = 6,
        wallIndex = [[default_wall]],
        dir = 6,
    },
}
local units =
{
    console =
    {
        spawnChance = 0.33,
        maxCount = 1,
        {
            {
                x = 1,
                y = 4,
                template = [[console]],
                unitData =
                {
                    facing = 0,
                },
            },
            1,
        },
    },
}
local decos =
{
}
local lights =
{
}
local sounds =
{
}
local export =
{
    cgraph =
    {
        edges =
        {
            {
                id0 = 100,
                x0 = 1,
                y0 = 2,
                id1 = 1,
                x1 = 0,
                y1 = 2,
            },
            {
                id0 = 100,
                x0 = 1,
                y0 = 3,
                id1 = 2,
                x1 = 0,
                y1 = 3,
            },
            {
                id0 = 100,
                x0 = 1,
                y0 = 4,
                id1 = 3,
                x1 = 0,
                y1 = 4,
            },
            {
                id0 = 100,
                x0 = 1,
                y0 = 5,
                id1 = 4,
                x1 = 0,
                y1 = 5,
            },
            {
                id0 = 100,
                x0 = 1,
                y0 = 1,
                id1 = 5,
                x1 = 0,
                y1 = 1,
            },
            {
                id0 = 6,
                x0 = 2,
                y0 = 0,
                id1 = 100,
                x1 = 2,
                y1 = 1,
            },
            {
                id0 = 7,
                x0 = 3,
                y0 = 0,
                id1 = 100,
                x1 = 3,
                y1 = 1,
            },
            {
                id0 = 8,
                x0 = 1,
                y0 = 0,
                id1 = 100,
                x1 = 1,
                y1 = 1,
            },
            {
                id0 = 9,
                x0 = 4,
                y0 = 1,
                id1 = 100,
                x1 = 3,
                y1 = 1,
            },
            {
                id0 = 10,
                x0 = 4,
                y0 = 2,
                id1 = 100,
                x1 = 3,
                y1 = 2,
            },
            {
                id0 = 11,
                x0 = 4,
                y0 = 3,
                id1 = 100,
                x1 = 3,
                y1 = 3,
            },
            {
                id0 = 12,
                x0 = 4,
                y0 = 4,
                id1 = 100,
                x1 = 3,
                y1 = 4,
            },
            {
                id0 = 13,
                x0 = 4,
                y0 = 5,
                id1 = 100,
                x1 = 3,
                y1 = 5,
            },
            {
                id0 = 100,
                x0 = 3,
                y0 = 5,
                id1 = 14,
                x1 = 3,
                y1 = 6,
            },
            {
                id0 = 100,
                x0 = 2,
                y0 = 5,
                id1 = 15,
                x1 = 2,
                y1 = 6,
            },
            {
                id0 = 100,
                x0 = 1,
                y0 = 5,
                id1 = 16,
                x1 = 1,
                y1 = 6,
            },
            {
                id0 = 3,
                x0 = 0,
                y0 = 4,
                id1 = 100,
                x1 = 1,
                y1 = 4,
            },
        },
    },
    width = 3,
    height = 5,
    version = 1,
    tiles = tiles,
    walls = walls,
    units = units,
    decos = decos,
    lights = lights,
    sounds = sounds,
}
return export
