-- Autogenerated lua file by the Spyface tool
-- 'Wimps and posers -- leave the hall! -- ManOwaR
--
-- DO NOT HAND EDIT.
--
local tiles =
{
    {
        x = 2,
        y = 3,
        zone = [[vault]],
        variant = 2,
        tags =
        {
            "noguard",
        },
    },
    {
        x = 2,
        y = 4,
        zone = [[vault]],
        variant = 2,
        tags =
        {
            "noguard",
        },
    },
    {
        x = 2,
        y = 5,
        zone = [[vault]],
        variant = 2,
        tags =
        {
            "noguard",
        },
    },
    {
        x = 6,
        y = 1,
        zone = [[vault]],
        variant = 0,
        dynamic_impass = 1,
    },
    {
        x = 6,
        y = 2,
        zone = [[vault]],
        variant = 0,
    },
    {
        x = 6,
        y = 3,
        zone = [[vault]],
        variant = 3,
    },
    {
        x = 6,
        y = 4,
        zone = [[vault]],
        variant = 3,
    },
    {
        x = 6,
        y = 5,
        zone = [[vault]],
        variant = 3,
    },
    {
        x = 6,
        y = 6,
        zone = [[vault]],
        variant = 0,
    },
    {
        x = 6,
        y = 7,
        zone = [[vault]],
        variant = 0,
        dynamic_impass = 1,
    },
    {
        x = 7,
        y = 1,
        zone = [[vault]],
        variant = 0,
    },
    {
        x = 7,
        y = 2,
        zone = [[vault]],
        variant = 0,
    },
    {
        x = 7,
        y = 3,
        zone = [[vault]],
        variant = 3,
        dynamic_impass = 1,
    },
    {
        x = 7,
        y = 4,
        zone = [[vault]],
        variant = 3,
        dynamic_impass = 1,
    },
    {
        x = 7,
        y = 5,
        zone = [[vault]],
        variant = 3,
    },
    {
        x = 7,
        y = 6,
        zone = [[vault]],
        variant = 0,
    },
    {
        x = 7,
        y = 7,
        zone = [[vault]],
        variant = 0,
    },
    {
        x = 8,
        y = 1,
        zone = [[vault]],
        variant = 0,
        dynamic_impass = 1,
    },
    {
        x = 8,
        y = 2,
        zone = [[vault]],
        variant = 0,
    },
    {
        x = 8,
        y = 3,
        zone = [[vault]],
        variant = 3,
    },
    {
        x = 8,
        y = 4,
        zone = [[vault]],
        variant = 3,
    },
    {
        x = 8,
        y = 5,
        zone = [[vault]],
        variant = 3,
    },
    {
        x = 8,
        y = 6,
        zone = [[vault]],
        variant = 0,
    },
    {
        x = 8,
        y = 7,
        zone = [[vault]],
        variant = 0,
        dynamic_impass = 1,
    },
    {
        x = 9,
        y = 3,
        zone = [[vault]],
        variant = 2,
    },
    {
        x = 9,
        y = 4,
        zone = [[vault]],
        variant = 2,
    },
    {
        x = 9,
        y = 5,
        zone = [[vault]],
        variant = 2,
    },
    {
        x = 3,
        y = 3,
        zone = [[vault]],
        variant = 2,
        tags =
        {
            "noguard",
        },
    },
    {
        x = 4,
        y = 3,
        zone = [[vault]],
        variant = 2,
        tags =
        {
            "noguard",
        },
    },
    {
        x = 5,
        y = 3,
        zone = [[vault]],
        variant = 2,
        tags =
        {
            "noguard",
        },
    },
    {
        x = 3,
        y = 4,
        zone = [[vault]],
        variant = 2,
        tags =
        {
            "noguard",
        },
        dynamic_impass = 1,
    },
    {
        x = 4,
        y = 4,
        zone = [[vault]],
        variant = 2,
        tags =
        {
            "noguard",
        },
    },
    {
        x = 5,
        y = 4,
        zone = [[vault]],
        variant = 2,
        tags =
        {
            "noguard",
        },
    },
    {
        x = 3,
        y = 5,
        zone = [[vault]],
        variant = 2,
        tags =
        {
            "noguard",
        },
    },
    {
        x = 4,
        y = 5,
        zone = [[vault]],
        variant = 2,
        tags =
        {
            "noguard",
        },
    },
    {
        x = 5,
        y = 5,
        zone = [[vault]],
        variant = 2,
        tags =
        {
            "noguard",
        },
    },
    {
        x = 9,
        y = 2,
        zone = [[vault]],
        variant = 1,
    },
    {
        x = 9,
        y = 6,
        zone = [[vault]],
        variant = 1,
    },
    {
        x = 10,
        y = 2,
        zone = [[vault]],
        variant = 1,
    },
    {
        x = 10,
        y = 3,
        zone = [[vault]],
        variant = 2,
    },
    {
        x = 10,
        y = 4,
        zone = [[vault]],
        variant = 2,
    },
    {
        x = 10,
        y = 5,
        zone = [[vault]],
        variant = 2,
    },
    {
        x = 10,
        y = 6,
        zone = [[vault]],
        variant = 1,
    },
    {
        x = 3,
        y = 2,
        zone = [[vault]],
        variant = 1,
        impass = 1,
        cover = 1,
    },
    {
        x = 4,
        y = 2,
        zone = [[vault]],
        variant = 1,
        tags =
        {
            "noguard",
        },
    },
    {
        x = 5,
        y = 2,
        zone = [[vault]],
        variant = 1,
        tags =
        {
            "noguard",
        },
    },
    {
        x = 2,
        y = 2,
        zone = [[vault]],
        variant = 1,
        impass = 1,
        cover = 1,
    },
    {
        x = 2,
        y = 6,
        zone = [[vault]],
        variant = 1,
        impass = 1,
        cover = 1,
    },
    {
        x = 3,
        y = 6,
        zone = [[vault]],
        variant = 1,
        tags =
        {
            "noguard",
        },
    },
    {
        x = 4,
        y = 6,
        zone = [[vault]],
        variant = 1,
        tags =
        {
            "noguard",
        },
    },
    {
        x = 5,
        y = 6,
        zone = [[vault]],
        variant = 1,
        tags =
        {
            "noguard",
        },
    },
    {
        x = 1,
        y = 5,
        zone = [[vault]],
        variant = 0,
        dynamic_impass = 1,
    },
    {
        x = 1,
        y = 4,
        zone = [[vault]],
        variant = 0,
        tags =
        {
            "noguard",
        },
    },
    {
        x = 1,
        y = 3,
        zone = [[vault]],
        variant = 0,
        dynamic_impass = 1,
    },
}
local walls =
{
    {
        x = 6,
        y = 0,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 6,
        y = 1,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 7,
        y = 0,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 7,
        y = 1,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 8,
        y = 0,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 8,
        y = 1,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 6,
        y = 1,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 5,
        y = 1,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 6,
        y = 7,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 5,
        y = 7,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 6,
        y = 7,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 6,
        y = 8,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 7,
        y = 7,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 7,
        y = 8,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 8,
        y = 7,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 8,
        y = 8,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 9,
        y = 1,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 8,
        y = 1,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 9,
        y = 7,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 8,
        y = 7,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 9,
        y = 6,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 9,
        y = 7,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 9,
        y = 1,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 9,
        y = 2,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 10,
        y = 1,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 10,
        y = 2,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 10,
        y = 6,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 10,
        y = 7,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 5,
        y = 1,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 5,
        y = 2,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 4,
        y = 1,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 4,
        y = 2,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 3,
        y = 1,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 3,
        y = 2,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 2,
        y = 1,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 2,
        y = 2,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 2,
        y = 2,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 1,
        y = 2,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 2,
        y = 6,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 1,
        y = 6,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 2,
        y = 6,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 2,
        y = 7,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 3,
        y = 6,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 3,
        y = 7,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 4,
        y = 6,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 4,
        y = 7,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 5,
        y = 6,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 5,
        y = 7,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 11,
        y = 2,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 10,
        y = 2,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 11,
        y = 3,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 10,
        y = 3,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 11,
        y = 4,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 10,
        y = 4,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 11,
        y = 5,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 10,
        y = 5,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 11,
        y = 6,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 10,
        y = 6,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 6,
        y = 2,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 5,
        y = 2,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 6,
        y = 3,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 5,
        y = 3,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 6,
        y = 5,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 5,
        y = 5,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 6,
        y = 6,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 5,
        y = 6,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 6,
        y = 4,
        wallIndex = [[vault_door]],
        dir = 4,
    },
    {
        x = 5,
        y = 4,
        wallIndex = [[vault_door]],
        dir = 0,
    },
    {
        x = 1,
        y = 5,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 1,
        y = 6,
        wallIndex = [[default_wall]],
        dir = 6,
    },
    {
        x = 1,
        y = 5,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 0,
        y = 5,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 1,
        y = 4,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 0,
        y = 4,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 1,
        y = 3,
        wallIndex = [[default_wall]],
        dir = 4,
    },
    {
        x = 0,
        y = 3,
        wallIndex = [[default_wall]],
        dir = 0,
    },
    {
        x = 1,
        y = 2,
        wallIndex = [[default_wall]],
        dir = 2,
    },
    {
        x = 1,
        y = 3,
        wallIndex = [[default_wall]],
        dir = 6,
    },
}
local units =
{
    {
        maxCount = 10,
        spawnChance = 1,
        {
            {
                x = 9,
                y = 2,
                template = [[security_laser_emitter_1x1]],
                unitData =
                {
                    facing = 2, traits = { startOn = true, powerGrid = "vault", powerGridName = "VAULT"  },
                },
            },
            1,
        },
        {
            {
                x = 6,
                y = 1,
                template = [[vault_safe_1]],
                unitData =
                {
                    facing = 2,
                    tags =
                    {
                        "vaultSafe",
                        "vault",
                    },
                },
            },
            1,
        },
        {
            {
                x = 6,
                y = 7,
                template = [[vault_safe_1]],
                unitData =
                {
                    facing = 6,
                    tags =
                    {
                        "vaultSafe",
                        "vault",
                    },
                },
            },
            1,
        },
        {
            {
                x = 8,
                y = 7,
                template = [[vault_safe_1]],
                unitData =
                {
                    facing = 6,
                    tags =
                    {
                        "vaultSafe",
                        "vault",
                    },
                },
            },
            1,
        },
        {
            {
                x = 7,
                y = 4,
                template = [[vault_processor]],
                unitData =
                {
                    facing = 0,
                    tags =
                    {
                        "vault",
                    },
                },
            },
            1,
        },
        {
            {
                x = 3,
                y = 4,
                template = [[vault_safe_2]],
                unitData =
                {
                    facing = 0, children = { "item_valuable_tech_2" }, traits = {inner_vault=true},
                    tags =
                    {
                        "vault",
                    },
                },
            },
            1,
        },
        {
            {
                x = 8,
                y = 1,
                template = [[vault_safe_1]],
                unitData =
                {
                    facing = 2,
                    tags =
                    {
                        "vaultSafe",
                        "vault",
                    },
                },
            },
            1,
        },
        {
            {
                x = 1,
                y = 5,
                template = [[vault_safe_1]],
                unitData =
                {
                    facing = 0, traits = {inner_vault=true},
                    tags =
                    {
                        "vaultSafe",
                        "vault",
                    },
                },
            },
            1,
        },
        {
            {
                x = 1,
                y = 3,
                template = [[vault_safe_1]],
                unitData =
                {
                    facing = 0, traits = {inner_vault=true},
                    tags =
                    {
                        "vaultSafe",
                        "vault",
                    },
                },
            },
            1,
        },
        {
            {
                x = 7,
                y = 3,
                template = [[laser_generator]],
                unitData =
                {
                    facing = 0, traits = { startOn = true, powerGrid = "vault", powerGridName = "VAULT" },
                },
            },
            1,
        },
    },
}
local decos =
{
    {
        x = 3,
        y = 2,
        kanim = [[vault_walllockerbig1]],
        facing = 2,
    },
    {
        x = 4,
        y = 6,
        kanim = [[vault_walllockerbig1]],
        facing = 6,
    },
    {
        x = 2,
        y = 2,
        kanim = [[vault_walllockersmall1]],
        facing = 0,
    },
    {
        x = 2,
        y = 6,
        kanim = [[vault_walllockersmall1]],
        facing = 0,
    },
    {
        x = 3,
        y = 2,
        kanim = [[vault_2x1_paintings2]],
        facing = 2,
    },
    {
        x = 2,
        y = 6,
        kanim = [[vault_1x1_paintings1]],
        facing = 6,
    },
    {
        x = 7,
        y = 1,
        kanim = [[decor_ko_barracks_walllight1]],
        facing = 2,
    },
    {
        x = 7,
        y = 7,
        kanim = [[decor_ko_barracks_walllight1]],
        facing = 6,
    },
    {
        x = 1,
        y = 4,
        kanim = [[decor_ko_barracks_walllight1]],
        facing = 0,
    },
    {
        x = 6,
        y = 3,
        kanim = [[decor_ceooffice_object_ceooffice_vaultlockside1]],
        facing = 0,
    },
    {
        x = 6,
        y = 5,
        kanim = [[decor_ceooffice_object_ceooffice_vaultlockside2]],
        facing = 0,
    },
    {
        x = 5,
        y = 5,
        kanim = [[decor_ceooffice_object_ceooffice_vaultlockside1]],
        facing = 4,
    },
    {
        x = 5,
        y = 3,
        kanim = [[decor_ceooffice_object_ceooffice_vaultlockside2]],
        facing = 4,
    },
}
local lights =
{
}
local sounds =
{
}
local export =
{
    cgraph =
    {
        edges =
        {
            {
                id0 = 0,
                x0 = 6,
                y0 = 0,
                id1 = 101,
                x1 = 6,
                y1 = 1,
            },
            {
                id0 = 2,
                x0 = 7,
                y0 = 0,
                id1 = 101,
                x1 = 7,
                y1 = 1,
            },
            {
                id0 = 3,
                x0 = 8,
                y0 = 0,
                id1 = 101,
                x1 = 8,
                y1 = 1,
            },
            {
                id0 = 101,
                x0 = 6,
                y0 = 1,
                id1 = 4,
                x1 = 5,
                y1 = 1,
            },
            {
                id0 = 101,
                x0 = 6,
                y0 = 7,
                id1 = 5,
                x1 = 5,
                y1 = 7,
            },
            {
                id0 = 101,
                x0 = 6,
                y0 = 7,
                id1 = 6,
                x1 = 6,
                y1 = 8,
            },
            {
                id0 = 101,
                x0 = 7,
                y0 = 7,
                id1 = 7,
                x1 = 7,
                y1 = 8,
            },
            {
                id0 = 101,
                x0 = 8,
                y0 = 7,
                id1 = 8,
                x1 = 8,
                y1 = 8,
            },
            {
                id0 = 9,
                x0 = 9,
                y0 = 1,
                id1 = 101,
                x1 = 8,
                y1 = 1,
            },
            {
                id0 = 10,
                x0 = 9,
                y0 = 7,
                id1 = 101,
                x1 = 8,
                y1 = 7,
            },
            {
                id0 = 101,
                x0 = 9,
                y0 = 6,
                id1 = 10,
                x1 = 9,
                y1 = 7,
            },
            {
                id0 = 9,
                x0 = 9,
                y0 = 1,
                id1 = 101,
                x1 = 9,
                y1 = 2,
            },
            {
                id0 = 11,
                x0 = 10,
                y0 = 1,
                id1 = 101,
                x1 = 10,
                y1 = 2,
            },
            {
                id0 = 101,
                x0 = 10,
                y0 = 6,
                id1 = 12,
                x1 = 10,
                y1 = 7,
            },
            {
                id0 = 4,
                x0 = 5,
                y0 = 1,
                id1 = 101,
                x1 = 5,
                y1 = 2,
            },
            {
                id0 = 13,
                x0 = 4,
                y0 = 1,
                id1 = 101,
                x1 = 4,
                y1 = 2,
            },
            {
                id0 = 14,
                x0 = 3,
                y0 = 1,
                id1 = 101,
                x1 = 3,
                y1 = 2,
            },
            {
                id0 = 15,
                x0 = 2,
                y0 = 1,
                id1 = 101,
                x1 = 2,
                y1 = 2,
            },
            {
                id0 = 101,
                x0 = 2,
                y0 = 2,
                id1 = 16,
                x1 = 1,
                y1 = 2,
            },
            {
                id0 = 101,
                x0 = 2,
                y0 = 6,
                id1 = 17,
                x1 = 1,
                y1 = 6,
            },
            {
                id0 = 101,
                x0 = 2,
                y0 = 6,
                id1 = 18,
                x1 = 2,
                y1 = 7,
            },
            {
                id0 = 101,
                x0 = 3,
                y0 = 6,
                id1 = 19,
                x1 = 3,
                y1 = 7,
            },
            {
                id0 = 101,
                x0 = 4,
                y0 = 6,
                id1 = 20,
                x1 = 4,
                y1 = 7,
            },
            {
                id0 = 101,
                x0 = 5,
                y0 = 6,
                id1 = 5,
                x1 = 5,
                y1 = 7,
            },
            {
                id0 = 21,
                x0 = 11,
                y0 = 2,
                id1 = 101,
                x1 = 10,
                y1 = 2,
            },
            {
                id0 = 22,
                x0 = 11,
                y0 = 3,
                id1 = 101,
                x1 = 10,
                y1 = 3,
            },
            {
                id0 = 23,
                x0 = 11,
                y0 = 4,
                id1 = 101,
                x1 = 10,
                y1 = 4,
            },
            {
                id0 = 24,
                x0 = 11,
                y0 = 5,
                id1 = 101,
                x1 = 10,
                y1 = 5,
            },
            {
                id0 = 25,
                x0 = 11,
                y0 = 6,
                id1 = 101,
                x1 = 10,
                y1 = 6,
            },
            {
                id0 = 101,
                x0 = 1,
                y0 = 5,
                id1 = 17,
                x1 = 1,
                y1 = 6,
            },
            {
                id0 = 101,
                x0 = 1,
                y0 = 5,
                id1 = 26,
                x1 = 0,
                y1 = 5,
            },
            {
                id0 = 101,
                x0 = 1,
                y0 = 4,
                id1 = 27,
                x1 = 0,
                y1 = 4,
            },
            {
                id0 = 101,
                x0 = 1,
                y0 = 3,
                id1 = 28,
                x1 = 0,
                y1 = 3,
            },
            {
                id0 = 16,
                x0 = 1,
                y0 = 2,
                id1 = 101,
                x1 = 1,
                y1 = 3,
            },
            {
                id0 = 0,
                x0 = 6,
                y0 = 0,
                id1 = 101,
                x1 = 6,
                y1 = 1,
            },
            {
                id0 = 4,
                x0 = 5,
                y0 = 1,
                id1 = 101,
                x1 = 6,
                y1 = 1,
            },
            {
                id0 = 6,
                x0 = 6,
                y0 = 8,
                id1 = 101,
                x1 = 6,
                y1 = 7,
            },
            {
                id0 = 5,
                x0 = 5,
                y0 = 7,
                id1 = 101,
                x1 = 6,
                y1 = 7,
            },
            {
                id0 = 9,
                x0 = 9,
                y0 = 1,
                id1 = 101,
                x1 = 8,
                y1 = 1,
            },
            {
                id0 = 3,
                x0 = 8,
                y0 = 0,
                id1 = 101,
                x1 = 8,
                y1 = 1,
            },
            {
                id0 = 8,
                x0 = 8,
                y0 = 8,
                id1 = 101,
                x1 = 8,
                y1 = 7,
            },
            {
                id0 = 10,
                x0 = 9,
                y0 = 7,
                id1 = 101,
                x1 = 8,
                y1 = 7,
            },
            {
                id0 = 14,
                x0 = 3,
                y0 = 1,
                id1 = 101,
                x1 = 3,
                y1 = 2,
            },
            {
                id0 = 15,
                x0 = 2,
                y0 = 1,
                id1 = 101,
                x1 = 2,
                y1 = 2,
            },
            {
                id0 = 16,
                x0 = 1,
                y0 = 2,
                id1 = 101,
                x1 = 2,
                y1 = 2,
            },
            {
                id0 = 18,
                x0 = 2,
                y0 = 7,
                id1 = 101,
                x1 = 2,
                y1 = 6,
            },
            {
                id0 = 17,
                x0 = 1,
                y0 = 6,
                id1 = 101,
                x1 = 2,
                y1 = 6,
            },
            {
                id0 = 17,
                x0 = 1,
                y0 = 6,
                id1 = 101,
                x1 = 1,
                y1 = 5,
            },
            {
                id0 = 26,
                x0 = 0,
                y0 = 5,
                id1 = 101,
                x1 = 1,
                y1 = 5,
            },
            {
                id0 = 16,
                x0 = 1,
                y0 = 2,
                id1 = 101,
                x1 = 1,
                y1 = 3,
            },
            {
                id0 = 28,
                x0 = 0,
                y0 = 3,
                id1 = 101,
                x1 = 1,
                y1 = 3,
            },
        },
    },
    width = 10,
    height = 7,
    version = 1,
    tiles = tiles,
    walls = walls,
    units = units,
    decos = decos,
    lights = lights,
    sounds = sounds,
}
return export
